# Generated by Django 2.0.4 on 2018-04-20 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180420_2109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='partido',
        ),
        migrations.AddField(
            model_name='team',
            name='partido',
            field=models.ManyToManyField(to='app.Partido'),
        ),
    ]
